### ISSUE TITLE
Uncaught Unhandled type 4096 libquassel.js:13886 in latest version of Chrome

### ISSUE THREAD

**Issue by rodneyrod** [magne4000/quassel-webserver#258]
Updated to latest version, updated per instructions in README.
Now when I login, I get to the 'Loading' screen but it doesn't proceed from there.
It can login in Firefox but some of the UI elements e.g. room has new messages and has changed colour, won't revert when clicking on that room and viewing it.

**Comment by magne4000** [comment]
What version of the core are you using ?
And do you have a more detailed stacktrace ?

**Comment by rodneyrod** [comment]
Core is quassel 0.12.2
I tried running it in verbose mode server side so I could see the outputs in my terminal but I couldn't see any errors, just loading style sheets.

**Comment by magne4000** [comment]
Hum, just in case, could you run the following command to cleanup and reinstall dependencies
`rm -rf node_modules && npm install --production` ?
Also, what `node` version are you using ?

**Comment by rodneyrod** [comment]
Node version is v6.9.5

I did what you said and it seems to be working again but I pretty much did this already by trashing my old folder and git cloning again with the same thing eventually happening again.

In your opinion, do you think this could be the server running out of RAM?

**Comment by rodneyrod** [comment]
I got some more from the JS console after rebooting the system after a fresh install of the node modules:

Uncaught RangeError: Trying to access beyond buffer length
    at checkOffset (libquassel.js:5525)
    at Uint8Array.readUInt32BE (libquassel.js:5584)
    at Reader.getUInt (libquassel.js:14020)
    at Reader.getByteArray (libquassel.js:13952)
    at Reader.getQVariantByType (libquassel.js:13858)
    at Iterator.next (libquassel.js:13159)
    at Reader.getQVariantByType (libquassel.js:13874)
    at Reader.getQVariant (libquassel.js:13915)
    at Reader.getList (libquassel.js:13966)
    at Reader.getQVariantByType (libquassel.js:13850)
4libquassel.js:5525 Uncaught RangeError: Trying to access beyond buffer length
    at checkOffset (libquassel.js:5525)
    at Uint8Array.readUInt32BE (libquassel.js:5584)
    at Reader.getUInt (libquassel.js:14020)
    at Reader.getByteArray (libquassel.js:13952)
    at Reader.getQVariantByType (libquassel.js:13858)
    at Iterator.next (libquassel.js:13159)
    at Reader.getQVariantByType (libquassel.js:13874)
    at Reader.getQVariant (libquassel.js:13915)
    at Reader.getList (libquassel.js:13966)
    at Reader.getQVariantByType (libquassel.js:13850)
checkOffset @ libquassel.js:5525
readUInt32BE @ libquassel.js:5584
Reader.getUInt @ libquassel.js:14020
Reader.getByteArray @ libquassel.js:13952
Reader.getQVariantByType @ libquassel.js:13858
next @ libquassel.js:13159
Reader.getQVariantByType @ libquassel.js:13874
Reader.getQVariant @ libquassel.js:13915
Reader.getList @ libquassel.js:13966
Reader.getQVariantByType @ libquassel.js:13850
Reader.getQVariant @ libquassel.js:13915
Reader.getList @ libquassel.js:13966
Reader.getQVariantByType @ libquassel.js:13850
Reader.getQVariant @ libquassel.js:13915
Reader.parse @ libquassel.js:13820
handleData @ libquassel.js:13351
(anonymous) @ libquassel.js:13303
EventEmitter.emit @ libquassel.js:4203
readableAddChunk @ libquassel.js:15195
Readable.push @ libquassel.js:15154
gotBuffer @ libquassel.js:21129
(anonymous) @ libquassel.js:21140
FileReader (async)
_ws.onmessage @ libquassel.js:21142

**Comment by rodneyrod** [comment]
If it's any help, it tells me it's failing at this part:

> if (offset + ext > length) throw new RangeError('Trying to access beyond buffer length')
> }

**Comment by magne4000** [comment]
Yeah there seems to be a real error, its odd, I'm wondering if anyone else is having the same issue.
Out of curiosity, which browser are you using / on what OS ?

**Comment by rodneyrod** [comment]
Chromium Version 65.0.3291.0 on Windows 10 64bit

**Comment by Gnarfoz** [comment]
I'm using `64.0.3282.39 (Official Build) beta (64-bit) (cohort: Beta)`, and I also only get past the login screen, then it stops working.

Lots of "write after end" error messages, probably caused by:
```
Connecting to quasselcore
angular-controller.js:1089 Logged in
libquassel.js:23295 ERROR Objectalert: {level: 2, description: 70}description: 70level: 2__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()message: "Incompatible TLS version."origin: "client"send: truetoString: ƒ ()arguments: nullcaller: nulllength: 0name: ""prototype: {constructor: ƒ}__proto__: ƒ ()[[FunctionLocation]]: libquassel.js:24187[[Scopes]]: Scopes[5]__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
angular-controller.js:1036 ERROR Objectalert: {level: 2, description: 70}description: 70level: 2__proto__: Objectmessage: "Incompatible TLS version."origin: "client"send: truetoString: ƒ ()arguments: nullcaller: nulllength: 0name: ""prototype: {constructor: ƒ}__proto__: ƒ ()[[FunctionLocation]]: libquassel.js:24187[[Scopes]]: Scopes[5]__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
libquassel.js:23295 ERROR Error: write after end
    at writeAfterEnd (libquassel.js:16334)
    at TLSSocket.Writable.write (libquassel.js:16374)
    at TLSSocket.Socket.write (libquassel.js:21011)
    at Socket.exports.Socket.write (libquassel.js:13283)
    at Quassel.requestBacklog (libquassel.js:23663)
    at libquassel.js:23200
    at Map.forEach (<anonymous>)
    at libquassel.js:23199
    at Map.forEach (<anonymous>)
    at Quassel.requestBacklogs (libquassel.js:23197)
angular-controller.js:1036 ERROR Error: write after end
    at writeAfterEnd (libquassel.js:16334)
    at TLSSocket.Writable.write (libquassel.js:16374)
    at TLSSocket.Socket.write (libquassel.js:21011)
    at Socket.exports.Socket.write (libquassel.js:13283)
    at Quassel.requestBacklog (libquassel.js:23663)
    at libquassel.js:23200
    at Map.forEach (<anonymous>)
    at libquassel.js:23199
    at Map.forEach (<anonymous>)
    at Quassel.requestBacklogs (libquassel.js:23197)
```


I'm not sure what kind of TLS version problem it could have.
I didn't change my TLS setup, and it's just nginx playing reverse proxy in front of quassel-webserver.

Clearly, something about Chrome must have changed, since it works in Firefox (57.0.3), but I'm not sure what.

**Comment by magne4000** [comment]
Yep, seems to come from Chrome/Chromium latest versions.
Sadly, I will not have time to dig into that until several months as I do not have a lot of free time at the moment.
